// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD67oTvqkboX0kgRgYKod5tXY4c_z-NUSo',
    appId: '1:70343076611:android:8acee06177a1ec7c2cd736',
    messagingSenderId: '70343076611',
    projectId: 'safehood-security-app',
    storageBucket: 'safehood-security-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDknygeIcbWcZG0gQ_ld5pFBWP7PabU5gg',
    appId: '1:70343076611:ios:ebb7ea29bd7cc0692cd736',
    messagingSenderId: '70343076611',
    projectId: 'safehood-security-app',
    storageBucket: 'safehood-security-app.firebasestorage.app',
    iosBundleId: 'com.safehood.securityapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmzycOZ3IgwuQvhRxlUj8-54bo_AIXQ6s',
    appId: '1:70343076611:web:b868fb096cfd22592cd736',
    messagingSenderId: '70343076611',
    projectId: 'safehood-security-app',
    authDomain: 'safehood-security-app.firebaseapp.com',
    storageBucket: 'safehood-security-app.firebasestorage.app',
  );
}
